// Generated by CoffeeScript 1.3.3
(function() {
  var endpoint, p, postToNakamap;

  p = function(message) {
    return console.log(message);
  };

  endpoint = 'https://im.handlena.me/api/post';

  postToNakamap = function(message) {
    var code, xhr;
    code = localStorage['group_code'];
    if (!code) {
      alert('Group code is not defined.\nPlease set code at options page.');
      return;
    }
    xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        return p("res: " + xhr.responseText);
      }
    };
    xhr.open('POST', "" + endpoint + "/" + code, false);
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.send("message=" + (encodeURI(message)));
    return p('post done');
  };

  chrome.contextMenus.create({
    title: 'post to nakamap',
    contexts: ['selection', 'link'],
    onclick: function(info, tab) {
      var message;
      message = info.linkUrl != null ? info.linkUrl : info.selectionText;
      return postToNakamap(message);
    }
  });

}).call(this);
