// Generated by CoffeeScript 1.3.3
(function() {

  window.addEventListener('load', function() {
    var codeE, doc, restoreOptions, saveOptions;
    doc = window.document;
    codeE = doc.getElementById('code');
    saveOptions = function() {
      console.log('save!!!');
      return localStorage['group_code'] = codeE.value;
    };
    restoreOptions = function() {
      var code;
      console.log('load!!!');
      code = localStorage['group_code'];
      if (!code) {
        return;
      }
      return codeE.value = code;
    };
    doc.getElementById('save').addEventListener('click', saveOptions);
    return restoreOptions();
  });

}).call(this);
